[package]
name = "ant_mania_sol"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name='benchmark'
harness=false

[profile.release]
debug = true
lto=false
opt-level=2